#!/bin/bash
#
# ddns-client
#
# A simple dynamic DNS client supporting dyndns.org for Linux.
#
# V. K. Karakasis       <vkarak@gmail.com>
#

program_name=$(basename $0)
config_file="/etc/ddns/ddns.conf"
pidfile="/var/run/$program_name.pid"
cachedir="/var/cache/ddns"

# Timeout in seconds for retrying after a non-critical failure
retry_timeout=60

logger_proginfo="$program_name[$$]"

#
# Handler for the TERM signal
#
# Do some cleanup and exit.
#
sigterm_handler()
{
    logger -p "user.info" -t "$logger_proginfo" \
        "Received the TERM signal. Exiting..."
    /bin/rm -f $pidfile
    exit 0
}

#
# Checks if the given IP is valid
#
is_valid_ip()
{
    is_valid=$(echo $1 | \
        grep -o '\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}')

    if [ -z $is_valid ]; then
        logger -p "user.error" -t "$logger_proginfo" \
            "\`$1' is not a valid IP address"
        return 1
    fi

    return 0
}

#
# Sleep interruptibly
#
sleep_int()
{
    if [ -z $1 ]; then
        return 0;
    fi

    sleep $1 &
    wait $! || return 1
    return 0
}

# Install signal handlers
trap sigterm_handler TERM

# Parse configuration file
if [ ! -e "$config_file" ]; then
    logger -p "user.error" -t "$logger_proginfo" \
        "\`$config_file' not found. Exiting..."
    exit 1
fi

service_name=$(grep -e '^name' "$config_file" | awk '{ print $2 }')
provider=$(grep -e '^provider' "$config_file" | awk '{ print $2 }')
hostname=$(grep -e '^hostname' "$config_file" | awk '{ print $2 }')
username=$(grep -e '^username' "$config_file" | awk '{ print $2 }')
password=$(grep -e '^password' "$config_file" | awk '{ print $2 }')
check_interval=$(grep -e '^check_interval' "$config_file" | awk '{ print $2 }')
force_interval=$(grep -e '^force_interval' "$config_file" | awk '{ print $2 }')

if [ -z $service_name ]; then
    logger -p "user.error" -t "$logger_proginfo" \
        "no service name specified. Exiting..."
    exit 1
fi

if [ -z $provider ]; then
    logger -p "user.warning" -t "$logger_proginfo" \
        "no provider specified. Assuming \`dyndns.org'."
    provider="dyndns.org"
fi

if [ "$provider" != "dyndns.org" ]; then
    logger -p "user.error" -t "$logger_proginfo" \
        "provider other than \`dyndns.org' provided. Exiting..."
    exit 1
fi

if [ -z $hostname ]; then
    logger -p "user.error" -t "$logger_proginfo" \
        "no hostname provided. Exiting..."
    exit 1
fi

if [ -z $username ]; then
    logger -p "user.error" -t "$logger_proginfo" \
        "no username provided. Exiting..."
    exit 1
fi

if [ -z $password ]; then
    logger -p "user.error" -t "$logger_proginfo" \
        "no pasword provided. Exiting..."
    exit 1
fi

if [ -z $check_interval ]; then
    logger -p "user.warning" -t "$logger_proginfo" \
        "no check interval specified. Assuming 10 min."
    check_interval=$((10*60))
fi

if [ -z $force_interval ]; then
    logger -p "user.warning" -t "$logger_proginfo" \
        "no force interval specified. Assuming 10 days."
    force_interval=$((10*24*3600))
fi

# Check if a client is already running and terminate it
if [ -e "$pidfile" ] && kill -0 $(cat "$pidfile") 2> /dev/null; then
    pid_to_kill=$(cat "$pidfile")
    logger -p "user.warning" -t "$logger_proginfo" \
        "another ddns-client[$pid_to_kill] is running."\
        "I will now terminate it."
    kill -TERM $pid_to_kill 2> /dev/null
fi

echo $$ > "$pidfile"

while [ true ]; do
    if [ ! -e "$cachedir/$service_name.ip" ]; then
        # Run DNS lookup to determine the registered IP. This is not safe,
        # however, and can lead to an abusive update, since the registered IP
        # might not have been propagated yet to your DNS server. It is
        # recommended to provide an initial IP file with the registered IP
        # address of your host at the time.
        logger -p "user.warning" -t "$logger_proginfo" \
            "ip file does not exist. I will run a DNS lookup."

        registered_ip=$(nslookup $hostname | grep -A1 $hostname | tail -n1 | \
            grep -o '\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}')
    else
        # Read the cached value
        registered_ip=$(cat "$cachedir/$service_name.ip")
    fi

    logger -p "user.info" -t "$logger_proginfo" \
        "checking registered ip... $registered_ip"

    if ! is_valid_ip "$registered_ip"; then
        logger -p "user.error" -t "$logger_proginfo" \
            "registered IP is invalid. I will retry after $retry_timeout sec."
        sleep_int $retry_timeout
        continue
    fi

    # Retrieve the current IP
    # Use absolute address to avoid DNS failures.
    # This is the address pool of `checkip.dyndns.com'.
    check_srv_pool="91.198.22.70 216.146.38.70 216.146.39.70"
    for srv_ip in $check_srv_pool; do
        current_ip=$(wget --tries 4 --timeout 3 -nv -O - \
            "http://$srv_ip" 2> /dev/null | \
            grep -o -e '\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}')
        logger -p "user.info" -t "$logger_proginfo" \
            "checking current IP from server $srv_ip... $current_ip"
        if is_valid_ip "$current_ip"; then
            break
        fi
    done

    if ! is_valid_ip "$current_ip"; then
        logger -p "user.error" -t "$logger_proginfo" \
            "could not retrieve the current IP address; i will retry after"\
            "$retry_timeout sec."
        sleep_int $retry_timeout
        continue
    fi

    # Check when was last update
    if [ ! -e "$cachedir/$service_name.update" ]; then
        logger -p "user.warning" -t "$logger_proginfo" \
            "could not retrieve the last update time, assuming last boot."
        last_update=$(grep -e '^btime' /proc/stat | awk '{ print $2 }')
    else
        last_update=$(cat "$cachedir/$service_name.update")
    fi

    current_time=$(date +%s)
    update_interval=$((current_time - last_update))

    if [ $update_interval -ge $force_interval ]; then
        logger -p "user.info" -t "$logger_proginfo" \
            "$update_interval sec have been elapsed since last update."\
            "Update will be forced."
        force_update="yes"
    else
        force_update="no"
    fi

    if [ $current_ip != $registered_ip ] || [ $force_update == "yes" ]; then
        logger -p "user.info" -t "$logger_proginfo" \
            "update is needed. Starting update process..."

        reply=$(wget -O - "https://$username:$password@members.dyndns.org/nic/update?hostname=$hostname&myip=$current_ip" 2> /dev/null)

        if [ -z "$reply" ]; then
            logger -p "user.warning" -t "$logger_proginfo" \
                "update did not reply. Your network might experience problems."
            continue
        fi

        logger -p "user.info" -t "$logger_proginfo" \
            "update process replied: $reply"

        # Check and interpret return code
        case "$reply" in
            "good $current_ip")
                logger -p "user.info" -t "$logger_proginfo" \
                    "Update was successful." ;;
            "nochg")
                logger -p "user.warning" -t "$logger_proginfo" \
                    "Abusive update. Cowardly exiting..."
                exit 1 ;;
            "badauth")
                logger -p "user.error" -t "$logger_proginfo" \
                    "Invalid username or password. Exiting..."
                exit 1 ;;
            "!donator")
                logger -p "user.error" -t "$logger_proginfo" \
                    "An option specified is only available to credited users."
                    " Exiting..."
                exit 1 ;;
            "notfqdn")
                logger -p "user.error" -t "$logger_proginfo" \
                    "Hostname is not a fully-qualified domain name. Exiting..."
                exit 1 ;;
            "nohost")
                logger -p "user.error" -t "$logger_proginfo" \
                    "The hostname specified does not exist. Exiting..."
                exit 1 ;;
            "numhost")
                logger -p "user.error" -t "$logger_proginfo" \
                    "Too many hosts. Exiting..."
                exit 1 ;;
            "abuse")
                logger -p "user.error" -t "$logger_proginfo" \
                    "Hostname is blocked for abuse."
                continue ;;
            "badagent")
                logger -p "user.error" -t "$logger_proginfo" \
                    "User agent was not sent or HTTP method is not permitted."
                    "Exiting..."
                exit 1 ;;
            "good 127.0.0.1")
                logger -p "user.error" -t "$logger_proginfo" \
                    "Update request ignored."
                continue ;;
            "dnserr")
                logger -p "user.error" -t "$logger_proginfo" \
                    "DNS error."
                continue ;;
            "911")
                logger -p "user.error" -t "$logger_proginfo" \
                    "Internal server error."
                continue ;;
            *)
                logger -p "user.info" -t "$logger_proginfo" \
                    "Unexpected error. Exiting..."
                exit 2 ;;
        esac

        # Update was successful; update your logs
        registered_ip=$current_ip
        echo $registered_ip > "$cachedir/$service_name.ip"
        echo $current_time > "$cachedir/$service_name.update"
    else
        logger -p "user.info" -t "$logger_proginfo" \
            "update is not needed."
    fi

    sleep_int $check_interval
done
